### ISSUE TITLE
Order Status on test account pending

### ISSUE THREAD

**Issue by vmasciotta** [hipay/hipay-fullservice-sdk-magento1#111]
Hi,
I'm testing this module on a test account.
I've made all the configurations as described in documentation.

After I place an order as guest or registered user and I set Visa or Mastercard payment in IFrame mode, the order status doesn't change. It stays on pending. 
I'd like to know if this behaviour is normal when it works with test account or if I'm missing something else.

Thanks.

**Comment by jprotin** [comment]
Hi Valerio,

Did you configure your method payment in authorization or sale ?

authorization is a manual capture, sale is an automatic capture.

In the back office HiPay, Did you configure the URL notification for Magento ?
Because after the success payment, HiPay call your Magento through callbacks and change the order status.

thank you, if you have more questions contact us pi-commerce@hipay.com

**Comment by maxcamo** [comment]
Now i'ts ok, there was a TYPO on the Notfy URL

Regards :)

**Comment by jprotin** [comment]
Ok i closed this issue
